export interface ChallengeTemplate {
  id: string;
  name: string;
  emoji: string;
  category: ChallengeCategory;
  description: string;
  trackReps: boolean;
  goalUnit?: string;
  defaultGoal?: number;
  suggestedDuration: number; // dni
}

export type ChallengeCategory =
  | "fitness"
  | "health"
  | "productivity"
  | "mindfulness"
  | "lifestyle";

export const CATEGORY_INFO: Record<ChallengeCategory, { label: string; emoji: string; color: string }> = {
  fitness: { label: "Fitness", emoji: "💪", color: "text-red-400" },
  health: { label: "Zdrowie", emoji: "❤️", color: "text-emerald-400" },
  productivity: { label: "Produktywność", emoji: "📚", color: "text-blue-400" },
  mindfulness: { label: "Mindfulness", emoji: "🧘", color: "text-violet-400" },
  lifestyle: { label: "Styl życia", emoji: "✨", color: "text-amber-400" },
};

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
  // FITNESS
  {
    id: "pushups",
    name: "Pompki",
    emoji: "💪",
    category: "fitness",
    description: "Codzienne pompki dla silniejszych ramion i klatki piersiowej",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 20,
    suggestedDuration: 30,
  },
  {
    id: "squats",
    name: "Przysiady",
    emoji: "🦵",
    category: "fitness",
    description: "Przysiady wzmacniające nogi i pośladki",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 30,
    suggestedDuration: 30,
  },
  {
    id: "burpees",
    name: "Burpees",
    emoji: "🔥",
    category: "fitness",
    description: "Intensywne ćwiczenie angażujące całe ciało",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 10,
    suggestedDuration: 30,
  },
  {
    id: "plank",
    name: "Plank",
    emoji: "🧱",
    category: "fitness",
    description: "Wzmocnij core trzymając pozycję deski",
    trackReps: true,
    goalUnit: "sekund",
    defaultGoal: 60,
    suggestedDuration: 30,
  },
  {
    id: "running",
    name: "Bieganie",
    emoji: "🏃",
    category: "fitness",
    description: "Codzienny bieg dla lepszej kondycji",
    trackReps: true,
    goalUnit: "km",
    defaultGoal: 3,
    suggestedDuration: 30,
  },
  {
    id: "jumping-jacks",
    name: "Pajacyki",
    emoji: "⭐",
    category: "fitness",
    description: "Proste ćwiczenie cardio na rozgrzewkę",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 50,
    suggestedDuration: 21,
  },
  {
    id: "situps",
    name: "Brzuszki",
    emoji: "🎯",
    category: "fitness",
    description: "Wzmocnij mięśnie brzucha",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 30,
    suggestedDuration: 30,
  },
  {
    id: "lunges",
    name: "Wykroki",
    emoji: "🚶",
    category: "fitness",
    description: "Ćwiczenie na nogi i równowagę",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 20,
    suggestedDuration: 30,
  },
  {
    id: "pullups",
    name: "Podciąganie",
    emoji: "🏋️",
    category: "fitness",
    description: "Podciąganie na drążku - siła pleców i ramion",
    trackReps: true,
    goalUnit: "powtórzeń",
    defaultGoal: 5,
    suggestedDuration: 30,
  },
  {
    id: "stretching",
    name: "Rozciąganie",
    emoji: "🤸",
    category: "fitness",
    description: "Codzienna sesja rozciągania dla elastyczności",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 10,
    suggestedDuration: 21,
  },

  // HEALTH
  {
    id: "water",
    name: "Pij wodę",
    emoji: "💧",
    category: "health",
    description: "Wypij odpowiednią ilość wody każdego dnia",
    trackReps: true,
    goalUnit: "szklanek",
    defaultGoal: 8,
    suggestedDuration: 30,
  },
  {
    id: "sleep-8h",
    name: "8 godzin snu",
    emoji: "😴",
    category: "health",
    description: "Śpij minimum 8 godzin każdej nocy",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "no-sugar",
    name: "Bez cukru",
    emoji: "🚫",
    category: "health",
    description: "Ogranicz cukier w diecie",
    trackReps: false,
    suggestedDuration: 21,
  },
  {
    id: "vegetables",
    name: "Jedz warzywa",
    emoji: "🥗",
    category: "health",
    description: "Jedz warzywa przy każdym posiłku",
    trackReps: true,
    goalUnit: "porcji",
    defaultGoal: 3,
    suggestedDuration: 30,
  },
  {
    id: "vitamins",
    name: "Witaminy",
    emoji: "💊",
    category: "health",
    description: "Pamiętaj o codziennych witaminach",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "no-alcohol",
    name: "Bez alkoholu",
    emoji: "🍷",
    category: "health",
    description: "Wyzwanie bez alkoholu",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "walk-steps",
    name: "10 000 kroków",
    emoji: "👟",
    category: "health",
    description: "Zrób 10 000 kroków dziennie",
    trackReps: true,
    goalUnit: "kroków",
    defaultGoal: 10000,
    suggestedDuration: 30,
  },
  {
    id: "healthy-breakfast",
    name: "Zdrowe śniadanie",
    emoji: "🍳",
    category: "health",
    description: "Zacznij dzień od zdrowego śniadania",
    trackReps: false,
    suggestedDuration: 21,
  },

  // PRODUCTIVITY
  {
    id: "reading",
    name: "Czytanie",
    emoji: "📖",
    category: "productivity",
    description: "Czytaj książkę każdego dnia",
    trackReps: true,
    goalUnit: "stron",
    defaultGoal: 20,
    suggestedDuration: 30,
  },
  {
    id: "learning",
    name: "Nauka",
    emoji: "🎓",
    category: "productivity",
    description: "Ucz się czegoś nowego każdego dnia",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 30,
    suggestedDuration: 30,
  },
  {
    id: "no-social-media",
    name: "Bez social media",
    emoji: "📵",
    category: "productivity",
    description: "Ogranicz czas na mediach społecznościowych",
    trackReps: false,
    suggestedDuration: 7,
  },
  {
    id: "early-wake",
    name: "Wstawaj o 6:00",
    emoji: "⏰",
    category: "productivity",
    description: "Wstawaj wcześnie każdego dnia",
    trackReps: false,
    suggestedDuration: 21,
  },
  {
    id: "writing",
    name: "Pisanie",
    emoji: "✍️",
    category: "productivity",
    description: "Pisz codziennie - dziennik, blog, książka",
    trackReps: true,
    goalUnit: "słów",
    defaultGoal: 500,
    suggestedDuration: 30,
  },
  {
    id: "coding",
    name: "Programowanie",
    emoji: "💻",
    category: "productivity",
    description: "Codzienne programowanie i rozwój umiejętności",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 60,
    suggestedDuration: 30,
  },
  {
    id: "language",
    name: "Nauka języka",
    emoji: "🌍",
    category: "productivity",
    description: "Ucz się nowego języka każdego dnia",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 15,
    suggestedDuration: 30,
  },
  {
    id: "inbox-zero",
    name: "Inbox Zero",
    emoji: "📧",
    category: "productivity",
    description: "Oczyść skrzynkę mailową każdego dnia",
    trackReps: false,
    suggestedDuration: 14,
  },

  // MINDFULNESS
  {
    id: "meditation",
    name: "Medytacja",
    emoji: "🧘",
    category: "mindfulness",
    description: "Codzienna praktyka medytacji",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 10,
    suggestedDuration: 30,
  },
  {
    id: "gratitude",
    name: "Wdzięczność",
    emoji: "🙏",
    category: "mindfulness",
    description: "Zapisz 3 rzeczy za które jesteś wdzięczny",
    trackReps: true,
    goalUnit: "rzeczy",
    defaultGoal: 3,
    suggestedDuration: 30,
  },
  {
    id: "journaling",
    name: "Dziennik",
    emoji: "📔",
    category: "mindfulness",
    description: "Prowadź dziennik swoich myśli",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "breathing",
    name: "Ćwiczenia oddechowe",
    emoji: "🌬️",
    category: "mindfulness",
    description: "Praktykuj świadome oddychanie",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 5,
    suggestedDuration: 21,
  },
  {
    id: "no-phone-morning",
    name: "Poranek bez telefonu",
    emoji: "📱",
    category: "mindfulness",
    description: "Pierwsza godzina dnia bez telefonu",
    trackReps: false,
    suggestedDuration: 14,
  },
  {
    id: "nature-time",
    name: "Czas na łonie natury",
    emoji: "🌳",
    category: "mindfulness",
    description: "Spędź czas na zewnątrz każdego dnia",
    trackReps: true,
    goalUnit: "minut",
    defaultGoal: 30,
    suggestedDuration: 30,
  },

  // LIFESTYLE
  {
    id: "clean-room",
    name: "Posprzątaj pokój",
    emoji: "🧹",
    category: "lifestyle",
    description: "Utrzymuj porządek w swoim otoczeniu",
    trackReps: false,
    suggestedDuration: 21,
  },
  {
    id: "make-bed",
    name: "Ściel łóżko",
    emoji: "🛏️",
    category: "lifestyle",
    description: "Zacznij dzień od ścielenia łóżka",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "cold-shower",
    name: "Zimny prysznic",
    emoji: "🚿",
    category: "lifestyle",
    description: "Rozpocznij dzień zimnym prysznicem",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "no-coffee",
    name: "Bez kawy",
    emoji: "☕",
    category: "lifestyle",
    description: "Wyzwanie bez kofeiny",
    trackReps: false,
    suggestedDuration: 7,
  },
  {
    id: "skincare",
    name: "Pielęgnacja skóry",
    emoji: "🧴",
    category: "lifestyle",
    description: "Codzienna rutyna pielęgnacyjna",
    trackReps: false,
    suggestedDuration: 30,
  },
  {
    id: "meal-prep",
    name: "Przygotuj posiłki",
    emoji: "🍱",
    category: "lifestyle",
    description: "Planuj i przygotowuj posiłki z wyprzedzeniem",
    trackReps: false,
    suggestedDuration: 21,
  },
  {
    id: "save-money",
    name: "Oszczędzaj",
    emoji: "💰",
    category: "lifestyle",
    description: "Odkładaj pieniądze każdego dnia",
    trackReps: true,
    goalUnit: "zł",
    defaultGoal: 10,
    suggestedDuration: 30,
  },
  {
    id: "compliment",
    name: "Powiedz komplement",
    emoji: "💬",
    category: "lifestyle",
    description: "Powiedz komuś miły komplement każdego dnia",
    trackReps: false,
    suggestedDuration: 21,
  },
];

export function getTemplatesByCategory(category: ChallengeCategory): ChallengeTemplate[] {
  return CHALLENGE_TEMPLATES.filter(t => t.category === category);
}

export function getAllCategories(): ChallengeCategory[] {
  return Object.keys(CATEGORY_INFO) as ChallengeCategory[];
}
